baseURL = "http://localhost:1313/"
languageCode = "en-nz"
title = "Water Outages"
theme = "vue-barebone"
copyright = "© {year} A. Huang (axkeyz)"

disablePathToLower = true

[permalinks]
    page = "/:filename"

[menu]
    [[menu.vb]]
    name = "Outages"
    identifier = "outages"
    weight = 1

    [[menu.vb]]
    name = "Dashboard"
    parent = "outages"
    url = "/"
    weight = 1
    pre = "svg/dashboard.svg"

    [[menu.vb]]
    name = "Analytics"
    url = "/analytics"
    parent = "outages"
    weight = 2
    pre = "svg/graph.svg"

    [[menu.vb]]
    name = "All Records"
    url = "/archive"
    parent = "outages"
    weight = 3
    pre = "svg/table.svg"

    [[menu.vb]]
    name = "Pipe Network"
    url = "/network"
    weight = 4
    pre = "svg/network.svg"

    [[menu.vb]]
    name = "Utilities"
    identifier = "utilities"
    weight = 5

    [[menu.vb]]
    name = "Settings"
    parent = "utilities"
    url = "/settings"
    weight = 6
    pre = "svg/settings.svg"

    [[menu.vb]]
    name = "About"
    parent = "utilities"
    url = "/modals/about"
    weight = 7
    pre = "svg/info.svg"
    [menu.vb.params]
        type = "modal"
        content = true
        url = "/modals/about"